version: '2'

networks:
  &network fitnessenet:
    driver: bridge

services:
  petclinic:
    restart: always
    image: migueltanada/petclinic:latest
    ports:
      - "9966:9966"
    networks:
      - *network

  mysql:
    restart: always
    image: mysql:5.7.8
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: "petclinic"
      MYSQL_ROOT_PASSWORD: "petclinic"
      MYSQL_USER: "petclinic"
      MYSQL_PASSWORD: "petclinic"
    networks:
      - *network


